import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Component1 from './component1'
import Component2 from './component2'
import Component3 from './component3'
import Component4 from './component4'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        
        <h1>useState</h1>
        <Component1 caption="Component1 Button1 "/>
        <Component1 caption="Component1 Button2 "/>
        <br/><br/>
        <hr></hr>
        <h1>Custom Hook</h1>
        <Component2 caption="Component2 Button1 "/>
        <Component2 caption="Component2 Button2 "/>
        <br/><br/>
        <hr></hr>
        <h1>Custom Hook NoMemo</h1>
        <Component3 caption="Component3 Button1 "/>
        <Component3 caption="Component3 Button2 "/>
        <br/><br/>
        <hr></hr>
        <h1>Custom Hook With Memo</h1>
        <Component4 caption="Component4 Button1 "/>
        <Component4 caption="Component4 Button2 "/>
    </>
  )
}
